import './globals.css';

export const metadata = {
  title: 'P2P Reports App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}